# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: brunocalza.me
email: brunoangelicalza@gmail.com
description: 
disqus_shortname: 'brunocalza'

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://brunocalza.me" # the base hostname & protocol for your site
enforce_ssl: brunocalza.me

author:
  name: 'Bruno Calza'
  email: brunoangelicalza@gmail.com
  twitter_username: brunocalza
  facebook_username: brunoangelicalza
  github_username:  brunoac
  linkedin_username:  brunocalza

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['Gemfile', 'Gemfile.lock']